import type { Metadata } from 'next';
import { inter, manrope } from './fonts';
import './reset.css';
import './globals.css';
import 'modern-normalize';
import Header from '@/components/Header/Header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${manrope.variable}`}>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
